[project]
name = "fastapi-test"
version = "1.0.0"
description = ""
authors = [
    {name = "Redlnn", email = "w731347477@gmail.com"},
]
dependencies = [
    "aiosqlite",
    "asyncmy",
    "fastapi",
    "loguru",
    "MCDReforged",
    "orjson",
    "passlib[bcrypt]",
    "pydantic",
    "python-jose[cryptography]",
    "python-multipart",
    "sqlalchemy[asyncio]",
    "uvicorn[standard]",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool]

[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    "isort",
    "black",
]

[tool.black]
line-length = 120
target-version = ["py310", "py311"]

[tool.isort]
profile = "black"
